### ISSUE TITLE
Sch.lua

### ISSUE THREAD

**Issue by frankshotdogs** [Kinematics/GearSwap-Jobs#18]
I have included this file and have noticed that the pedagogy loafers do not load when you use ja then i tried other items and it seems to be the case for all gear for job ability. I downloaded the Brd.lua and the ja gear changes with no problem. Thanks for the help Im new to this program so my be user error.

**Comment by Kinematics** [comment]
Sorry for not seeing this issue for several months.

The only JAs Pedagogy Loafers would be associated with are Celerity and Alacrity (and the, only with weather active).  They will not be used when you use the JA, because these types of effects require the gear to be equipped when you're casting a spell while that effect is active.

In other words, they'd never be equipped when you use Celerity, on when you cast a spell (while weather is up) when you have the Celerity buff active already.

Closing this issue.  If you have other issues, I'll be keeping a closer eye on notifications from now on.
