### ISSUE TITLE
SMN error

### ISSUE THREAD

**Issue by geekgirl101** [Kinematics/GearSwap-Jobs#61]
I'm getting a "Gearswap has detected an error in the user function self_command....attempt to concatenate field 'name' (a nil value)" error on the following line:

```
    add_to_chat(122,pet.name..' does not have a pact of type ['..pact..'].')
```

**Comment by Kinematics** [comment]
You'll need to give me more information.  What avatar did you have out, and which command were you trying to give it?

A quick test of my own is not giving me this error.

**Comment by geekgirl101** [comment]
Ah, it occurs when trying to use a bloodpact when there is no avatar present.

**Comment by Kinematics** [comment]
It shouldn't be possible to even reach that code line if there is no pet present.  It should bail out when it checks for pet.isvalid.

Further, it shouldn't be possible for that line to generate an error, since it's _immediately_ after a check for `pacts[pact][pet.name]`, which obviously checks pet.name, which is the same field that's generating an error in your `add_to_chat` function.

And finally, even without an avatar out, I can't reproduce your problem.  You're going to need to give me _exact_ steps to generate this error, as well as an indication of whether you have modified this job file at all.

**Comment by geekgirl101** [comment]
I believe it to be because I had commented out parts of the code including entire functions related to macro book swapping since I don't swap books with avatars.  I recently undid all that and just commented out specific lines for changing macros rather then the entire function and that fixed the problem.  Can't believe I was so stupid, I must've been half asleep when I commented out the whole function that handled whether a pet was active or not.
