### ISSUE TITLE
Wanting to discuss certain gear admissions/omissions

### ISSUE THREAD

**Issue by geekgirl101** [Kinematics/GearSwap-Jobs#69]
I noticed in the Mote-Utility.lua that Twilight Cape and Zodiac Ring are given names for gear.ElementalRing.name and gear.ElementalCape.name, but I don't see those being used in any of the job files.  I was wondering where these are being used and whether I should still bother carrying them around.

I noticed also the omission of certain "useful" items and was wondering why this was the case.  For example:

*Pentalagus Charm offers +2 steal but isn't included in the steal set
*Haven Hose, Earthcry Earring and Stone Gorget enhance stoneskin effect but aren't included in midcast stoneskin set
*Carapacho Cuffs speeds up stoneskin casting but there is either no precast set for stoneskin or they aren't included
*Summoning Torque and Vox Grip offer small amounts of summoning skill but aren't being used for buff pacts (there is no default grip in the buff pact set)
*Estoqueur's Earring enhances fast cast but isn't included in precast fast cast sets

**Comment by sebyg666** [comment]
Hi i saw this and thaugh id try and help you out a bit. Motentons sets are there as examples. Those sets are by no means fixed. You can edit them with what ever you want. The cape and ring are like the magian fastcast staffs and the elemental gorgets, belts, and mage obis. You can easily utilize them in your gear sets. For example you may only have 2 of the 7 fast cast staffs. So you create a default staff in the globals ( gear.default.fastcast_staff =  "name the staff here" ) and then in your set  you can use 
main=gear.FastcastStaff

Now what it does is if the spell you'r casting has an element that matches one of you'r fastcast staffs, motentons files automaticly checks your inventory to see which staffs you have. If you dont have a matching staff it will equip your default one. This applies to obis ele belts and capes and in a similar manner the zodiac ring and twilight cape. The cape and ring you will also need to create defaults incase weather or day do not match the element of the spell, that way gearswap can select what peices of gear are best at the time.

gear.default.obi_waist = "Aswang sash"
gear.default.obi_back = "Toro Cape"
gear.default.obi_ring = "Strendu Ring"

put the above in your globals file (using what ever gear you actually have) and these will be equipped as defaults.

back=gear.ElementalCape, waist=gear.ElementalObi, ring1=gear.ElementalRing

put that in your midcast nuking gear and it will use the correct obi, cape and ring for your nuke, or default cape, obi and ring if you dont have them.

As for the stoneskin fast cast u can do this

sets.precast.FC = {
                main=gear.FastcastStaff,sub={name="Vivid Strap",order=2},
                head="Nahtirah hat",ear2="Loquac. Earring",
                body="Anhur Robe",hands="Repartie gloves",ring1="Prolix Ring",ring2='Veneficium Ring',
                back="Swith Cape",waist="Witful belt",legs="Orvail Pants",feet="Chelona Boots"}

sets.precast.FC['Enhancing Magic'] = set_combine(sets.precast.FC, {waist="Siegel Sash"})

sets.precast.FC.Stoneskin = set_combine(sets.precast.FC, sets.precast.FC['Enhancing Magic'], {hands="Carapacho Cuffs"})

This will basicly equip your standard fastcast set and then layer on top the set that adds fastcast to enhancing spells only (stoneskin is enhancing magic) and then the  stoneskin fast cast gear. And if you happen to have the magian earth fastcast staff it will equip it too. You'll notice for the sub (grip) theres an order number. this will force the grip to be equipped second. (i dont know currently how to make order be set for the main weapon because of the naming convension but you would set the staff as order 1 such that gearswap doesnt try to equip the grip first, just incase you were using a club and shield for example. you cant equip a grip with a club, so you'd want the staff equipped first then the grip.)

for the stoneskin midcast to equip stoneskin potency gear u can do something similar (these are my bard sets)

sets.midcast.FastRecast = {
                main={name="Lehbrailg +2",order=1},sub={name="Vivid Strap",order=2},range="Angel Lyre",
                head="Nahtirah Hat",ear2="Loquacious Earring",
                body="Anhur Robe",hands="Gendewitha Gages +1",ring1="Prolix Ring",
                back="Swith Cape",waist="Phasmida Belt",legs="Artsieq Hose",feet="Battlecast Gaiters"}

sets.midcast['Enhancing Magic'] = set_combine(sets.midcast.FastRecast, {
                main={name="Lehbrailg +2",order=1},sub={name="Fulcio Grip",order=2},
                neck="Colossus's Torque",
                back="Merciful Cape",waist="Olympus Sash",legs="Portent Pants"})

sets.midcast.Stoneskin = set_combine(sets.midcast.FastRecast, sets.midcas['Ehancing Magic']
                                        {neck="Stone Gorget",ear1='Earthcry Earring}

this will do for you exactly the same as the fast cast but for the midcast. itll equip ur fastrecast gear first, then layer on top enhancing gear, then stoneskin gear automatically.

You can do this for a lot of stuff. If you need any help im sure motenton or i can assist. Im not currently using his most up to date files so this code might need a bit of change but this is just a basic example of the power of motes files. Hope this helps you out.

Hope you enjoy.

**Comment by geekgirl101** [comment]
Ah right understood.  I may as well keep them around then since I'm not a big collector of individual items for every spell element. :)

And yeah I worked out how to do the set combine weeks ago.  Was just curious to why the items weren't already being included.

Didn't know about the order, I've had the game comment a few times about not being able to equip a grip without a 2H weapon, so I'll put those in there.

Thanks so much for the insight.

**Comment by sebyg666** [comment]
not a problem, anytime.
